name: Slack Notify Action
description: 利用Slack進行CI CD結果通知

inputs:
  token:
    description: Slack Bot Token
    required: true
  job-status:
    required: true
runs:
  using: "composite"
  steps:
    - name: CD結果通知
      if: ${{ vars.CD_NOTIFY_ENABLED == 'true' }}
      uses: slackapi/slack-github-action@v2.0.0
      env:
        STATUS_MSG: ${{ inputs.job-status == 'success' && vars.SUCCESS_MSG || vars.FAILURE_MSG }}
        BUILD_LINK: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_number }}
      with:
        method: chat.postMessage
        token: ${{ inputs.token }}
        payload: |
          channel: ${{ vars.SLACK_CHANNEL_ID }}
          text: "${{ github.event.repository.name }} ${{ github.ref_name }}版\n${{ github.workflow }}/${{ github.job }}\n${{ env.STATUS_MSG }}\nCommit: ${{ github.event.head_commit.message }}\nlogs: ${{ env.BUILD_LINK }}"
